import {
    architecture,
    bank,
    bycycle,
    car_station,
    car,
    coffee,
    culture,
    different,
    entertainment,
    food,
    history,
    industrial,
    major,
    nature,
    religion,
    shop,
    sport
  } from '../assets/myIcons';
  
  export const categories = [
    { icon: architecture, text: 'Архитектура' },
    { icon: bank, text: 'Банки' },
    { icon: bycycle, text: 'Велосипеды' },
    { icon: car_station, text: 'Заправки' },
    { icon: car, text: 'Авто' },
    { icon: coffee, text: 'Кофе/чай' },
    { icon: culture, text: 'Культура' },
    { icon: different, text: 'Разное' },
    { icon: entertainment, text: 'Развлечения' },
    { icon: food, text: 'Еда' },
    { icon: history, text: 'История' },
    { icon: industrial, text: 'Индустриальные объекты' },
    { icon: major, text: '18+' },
    { icon: nature, text: 'Природа' },
    { icon: religion, text: 'Религия' },
    { icon: shop, text: 'Магазины' },
    { icon: sport, text: 'Спорт' },
  ];